# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 17:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('home_score', models.PositiveIntegerField()),
                ('away_score', models.PositiveIntegerField()),
                ('ko_datetime', models.DateTimeField()),
                ('venue', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FixtureGuess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_guess', models.PositiveIntegerField()),
                ('away_guess', models.PositiveIntegerField()),
                ('winner', models.CharField(max_length=56)),
                ('margin', models.PositiveIntegerField()),
                ('total_points', models.PositiveIntegerField()),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_who_guessed', to='fixtures.Fixture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Bills', 'Bills'), ('Dolphins', 'Dolphins'), ('Patriots', 'Patriots'), ('Jets', 'Jets'), ('Ravens', 'Ravens'), ('Bengals', 'Bengals'), ('Browns', 'Browns'), ('Steelers', 'Steelers'), ('Texans', 'Texans'), ('Colts', 'Colts'), ('Jaguars', 'Jaguars'), ('Titans', 'Titans'), ('Broncos', 'Broncos'), ('Chiefs', 'Chiefs'), ('Raiders', 'Raiders'), ('Chargers', 'Chargers'), ('Cowboys', 'Cowboys'), ('Giants', 'Giants'), ('Eagles', 'Eagles'), ('Redskins', 'Redskins'), ('Bears', 'Bears'), ('Lions', 'Lions'), ('Packers', 'Packers'), ('Vikings', 'Vikings'), ('Falcons', 'Falcons'), ('Panthers', 'Panthers'), ('Saints', 'Saints'), ('Buccaneers', 'Buccaneers'), ('Cardinals', 'Cardinals'), ('Rams', 'Rams'), ('49ers', '49ers'), ('Seahawks', 'Seahawks')], max_length=56)),
            ],
        ),
        migrations.AddField(
            model_name='fixture',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='fixtures.Team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='guessers',
            field=models.ManyToManyField(through='fixtures.FixtureGuess', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='fixtures.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='fixtureguess',
            unique_together=set([('fixture', 'user')]),
        ),
    ]
