# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-16 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('away_score', models.PositiveIntegerField(blank=True)),
                ('home_score', models.PositiveIntegerField(blank=True)),
                ('week', models.PositiveIntegerField()),
                ('ko_datetime', models.DateTimeField(blank=True, null=True)),
                ('changeable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(choices=[('DEN', 'DEN'), ('CAR', 'CAR'), ('TB', 'TB'), ('ATL', 'ATL'), ('BAL', 'BAL'), ('BUF', 'BUF'), ('HOU', 'HOU'), ('CHI', 'CHI'), ('JAC', 'JAC'), ('GB', 'GB'), ('KC', 'KC'), ('LAC', 'LAC'), ('NO', 'NO'), ('OAK', 'OAK'), ('NYJ', 'NYJ'), ('CIN', 'CIN'), ('PHI', 'PHI'), ('CLE', 'CLE'), ('TEN', 'TEN'), ('MIN', 'MIN'), ('SEA', 'SEA'), ('MIA', 'MIA'), ('DAL', 'DAL'), ('NYG', 'NYG'), ('IND', 'IND'), ('DET', 'DET'), ('ARI', 'ARI'), ('NE', 'NE'), ('WAS', 'WAS'), ('PIT', 'PIT'), ('SF', 'SF'), ('LA', 'LA')], max_length=5, null=True)),
                ('city_name', models.CharField(max_length=50, null=True)),
                ('team_name', models.CharField(choices=[('Bills', 'Bills'), ('Dolphins', 'Dolphins'), ('Patriots', 'Patriots'), ('Jets', 'Jets'), ('Ravens', 'Ravens'), ('Bengals', 'Bengals'), ('Browns', 'Browns'), ('Steelers', 'Steelers'), ('Texans', 'Texans'), ('Colts', 'Colts'), ('Jaguars', 'Jaguars'), ('Titans', 'Titans'), ('Broncos', 'Broncos'), ('Chiefs', 'Chiefs'), ('Raiders', 'Raiders'), ('Chargers', 'Chargers'), ('Cowboys', 'Cowboys'), ('Giants', 'Giants'), ('Eagles', 'Eagles'), ('Redskins', 'Redskins'), ('Bears', 'Bears'), ('Lions', 'Lions'), ('Packers', 'Packers'), ('Vikings', 'Vikings'), ('Falcons', 'Falcons'), ('Panthers', 'Panthers'), ('Saints', 'Saints'), ('Buccaneers', 'Buccaneers'), ('Cardinals', 'Cardinals'), ('Rams', 'Rams'), ('49ers', '49ers'), ('Seahawks', 'Seahawks')], max_length=50, null=True)),
                ('full_name', models.CharField(max_length=50, null=True)),
                ('division', models.CharField(choices=[('AFC_EAST', 'AFC_EAST'), ('AFC_NORTH', 'AFC_NORTH'), ('AFC_SOUTH', 'AFC_SOUTH'), ('AFC_WEST', 'AFC_WEST'), ('NFC_EAST', 'NFC_EAST'), ('NFC_NORTH', 'NFC_NORTH'), ('NFC_SOUTH', 'NFC_SOUTH'), ('NFC_WEST', 'NFC_WEST')], max_length=50, null=True)),
                ('conference', models.CharField(choices=[('AFC', 'AFC'), ('NFC', 'NFC')], default='AFC', max_length=5, null=True)),
                ('team_logo', models.ImageField(blank=True, upload_to='logos')),
            ],
        ),
        migrations.AddField(
            model_name='fixture',
            name='away_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away', to='fixtures.Team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home', to='fixtures.Team'),
        ),
    ]
