# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='slug',
        ),
        migrations.AddField(
            model_name='fixture',
            name='week',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fixture',
            name='away_score',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='home_score',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='name',
            field=models.CharField(max_length=56, unique=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='venue',
            field=models.CharField(max_length=56),
        ),
        migrations.AlterField(
            model_name='fixtureguess',
            name='away_guess',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='fixtureguess',
            name='home_guess',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='fixtureguess',
            name='margin',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='fixtureguess',
            name='total_points',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='fixtureguess',
            name='winner',
            field=models.CharField(blank=True, max_length=56),
        ),
    ]
