# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0002_auto_20170625_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='week',
            field=models.CharField(choices=[('WK1', 'WK1'), ('WK2', 'WK2'), ('WK3', 'WK3'), ('WK4', 'WK4'), ('WK5', 'WK5'), ('WK6', 'WK6'), ('WK7', 'WK7'), ('WK8', 'WK8'), ('WK9', 'WK9'), ('WK10', 'WK10'), ('WK11', 'WK11'), ('WK12', 'WK12'), ('WK13', 'WK13'), ('WK14', 'WK14'), ('WK15', 'WK15'), ('WK16', 'WK16'), ('WK17', 'WK17'), ('WILDCARD', 'WILDCARD'), ('DIVISIONAL', 'DIVISIONAL'), ('CHAMPIONSHIP', 'CHAMPIONSHIP'), ('SUPERBOWL', 'SUPERBOWL')], max_length=56),
        ),
    ]
