# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0005_auto_20170625_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='guessers',
        ),
        migrations.AddField(
            model_name='team',
            name='team_logo',
            field=models.ImageField(blank=True, upload_to='logos'),
        ),
    ]
