# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0006_auto_20170626_1052'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fixtureguess',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='fixtureguess',
            name='fixture',
        ),
        migrations.RemoveField(
            model_name='fixtureguess',
            name='user',
        ),
        migrations.DeleteModel(
            name='FixtureGuess',
        ),
    ]
