# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0007_auto_20170626_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='venue',
        ),
        migrations.AddField(
            model_name='team',
            name='short_name',
            field=models.CharField(choices=[('DEN', 'DEN'), ('CAR', 'CAR'), ('TB', 'TB'), ('ATL', 'ATL'), ('BAL', 'BAL'), ('BUF', 'BUF'), ('HOU', 'HOU'), ('CHI', 'CHI'), ('JAC', 'JAC'), ('GB', 'GB'), ('KC', 'KC'), ('SD', 'SD'), ('NO', 'NO'), ('OAK', 'OAK'), ('NYJ', 'NYJ'), ('CIN', 'CIN'), ('PHI', 'PHI'), ('CLE', 'CLE'), ('TEN', 'TEN'), ('MIN', 'MIN'), ('SEA', 'SEA'), ('MIA', 'MIA'), ('DAL', 'DAL'), ('NYG', 'NYG'), ('IND', 'IND'), ('DET', 'DET'), ('ARI', 'ARI'), ('NE', 'NE'), ('WAS', 'WAS'), ('PIT', 'PIT'), ('SF', 'SF'), ('LA', 'LA')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='ko_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='week',
            field=models.PositiveIntegerField(),
        ),
    ]
