# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0008_auto_20170702_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
        migrations.AddField(
            model_name='team',
            name='city_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_name',
            field=models.CharField(choices=[('Bills', 'Bills'), ('Dolphins', 'Dolphins'), ('Patriots', 'Patriots'), ('Jets', 'Jets'), ('Ravens', 'Ravens'), ('Bengals', 'Bengals'), ('Browns', 'Browns'), ('Steelers', 'Steelers'), ('Texans', 'Texans'), ('Colts', 'Colts'), ('Jaguars', 'Jaguars'), ('Titans', 'Titans'), ('Broncos', 'Broncos'), ('Chiefs', 'Chiefs'), ('Raiders', 'Raiders'), ('Chargers', 'Chargers'), ('Cowboys', 'Cowboys'), ('Giants', 'Giants'), ('Eagles', 'Eagles'), ('Redskins', 'Redskins'), ('Bears', 'Bears'), ('Lions', 'Lions'), ('Packers', 'Packers'), ('Vikings', 'Vikings'), ('Falcons', 'Falcons'), ('Panthers', 'Panthers'), ('Saints', 'Saints'), ('Buccaneers', 'Buccaneers'), ('Cardinals', 'Cardinals'), ('Rams', 'Rams'), ('49ers', '49ers'), ('Seahawks', 'Seahawks')], max_length=50, null=True),
        ),
    ]
