# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0010_fixture_changeable'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='conference',
            field=models.CharField(choices=[('AFC', 'AFC'), ('NFC', 'NFC')], default='AFC', max_length=5, null=True),
        ),
    ]
