# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0011_team_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.CharField(choices=[('AFC_EAST', 'AFC_EAST'), ('AFC_NORTH', 'AFC_NORTH'), ('AFC_SOUTH', 'AFC_SOUTH'), ('AFC_WEST', 'AFC_WEST'), ('NFC_EAST', 'NFC_EAST'), ('NFC_NORTH', 'NFC_NORTH'), ('NFC_SOUTH', 'NFC_SOUTH'), ('NFC_WEST', 'NFC_WEST')], max_length=50, null=True),
        ),
    ]
