# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='total',
        ),
    ]
