# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 19:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fixtures', '0007_auto_20170626_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_pick', models.PositiveIntegerField(blank=True, null=True)),
                ('away_pick', models.PositiveIntegerField(blank=True, null=True)),
                ('winner', models.CharField(blank=True, max_length=56, null=True)),
                ('margin', models.PositiveIntegerField(blank=True, null=True)),
                ('total_points', models.PositiveIntegerField(blank=True, null=True)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_who_picked', to='fixtures.Fixture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
