# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='changeable',
            field=models.BooleanField(default=False),
        ),
    ]
