# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0002_pick_changeable'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='margin_pts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pick',
            name='totalpts_pts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pick',
            name='winner_pts',
            field=models.IntegerField(default=0),
        ),
    ]
