# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0003_auto_20170702_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pick',
            name='margin',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='total_points',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='winner',
        ),
    ]
