# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0004_auto_20170702_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='changeable',
            field=models.BooleanField(default=True),
        ),
    ]
