# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-09 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0007_auto_20170909_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pick',
            name='changeable',
        ),
    ]
