# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0010_remove_pick_changeable'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='lock',
            field=models.BooleanField(default=False),
        ),
    ]
