# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0013_auto_20170902_0942'),
        ('playoff_teams', '0003_auto_20170902_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='playoffpick',
            name='sb_runner_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sb_runner_up', to='fixtures.Team'),
        ),
        migrations.AddField(
            model_name='playoffpick',
            name='sb_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sb_winner', to='fixtures.Team'),
        ),
    ]
